version: "3.8"

services:
  eureka:
    container_name: twisted-fate
    build:
      context: ../../twistedfate
      dockerfile: Dockerfile
    restart: "no"
    networks:
      - common-network
    ports:
      - "8084:8084"

networks:
  common-network:
    external: true
